services:

  authorization-service:
    path: src/services/authorization/

  product-service:
    path: src/services/product/

  import-service:
    path: src/services/import/
    params:
      queueUrl: ${product-service.queueUrl}
