service: product-service

frameworkVersion: "3"

useDotenv: true

provider:
    name: aws
    runtime: nodejs14.x
    region: eu-west-1

plugins:
    - serverless-auto-swagger
    - serverless-offline

functions:

    getProductList:
        handler: src/lambdas/getProductsList/index.handler
        events:
            - http:
                method: GET
                path: /products
                cors: true

    getProductById:
        handler: src/lambdas/getProductById/index.handler
        events:
            - http:
                method: GET
                path: /products/{id}
                cors: true
                request:
                    parameters:
                        paths:
                            id: true
